Vagrant.configure("2") do |config|
 # config.vm.box = "boxomatic/centos-stream-9"

  config.vm.box = "centos/stream8"
  config.vm.box_version = "20210210.0"


# Forward the VM's port 9000 to the host's port 9000.  Later we'll run a 
# container, and forward the container's 9000 to the VM.
# This lets us access the web interface on 9000 from the pc via http://localhost:9000/
  config.vm.network :forwarded_port, guest: 9000, host: 9000, id: "sonarqube"

# Install the user's public key to allow SSH access, and private key to allow github access.
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
  config.vm.provision "shell", inline: <<-SHELL
    echo "Setting up SSH keys"
	cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
#	if [ -f /vagrant/known_hosts ]; then mv /vagrant/known_hosts /home/vagrant/.ssh/known_hosts; fi
#	chmod 644 /home/vagrant/.ssh/known_hosts
	chmod 644 /home/vagrant/.ssh/id_rsa.pub
	chmod 600 /home/vagrant/.ssh/id_rsa
  SHELL
  
  config.vm.provision "shell", inline: <<-SHELL
	yum update -y
	yum install -y docker wget 
	systemctl enable docker
	systemctl start docker
	docker pull sonarqube:latest
	docker container run -d --name sonarqube -p 9000:9000 sonarqube:latest
  SHELL


  
  
end